apiVersion: apps/v1
kind: Deployment
metadata:
  name: glasslab-nats
  namespace: glasslab-v2
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: glasslab-nats
  template:
    metadata:
      labels:
        app.kubernetes.io/name: glasslab-nats
    spec:
      nodeSelector:
        kubernetes.io/hostname: node05
      containers:
        - name: nats
          image: nats@sha256:b83efabe3e7def1e0a4a31ec6e078999bb17c80363f881df35edc70fcb6bb927
          imagePullPolicy: IfNotPresent
          args:
            - -js
            - -m
            - "8222"
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitoring
          readinessProbe:
            tcpSocket:
              port: client
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: client
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: nats-data
              mountPath: /data
      volumes:
        - name: nats-data
          persistentVolumeClaim:
            claimName: glasslab-nats-data
