ansible_become: true
containerd_package: containerd
container_runtime_socket: unix:///run/containerd/containerd.sock
containerd_sandbox_image: registry.k8s.io/pause:3.10.1@sha256:278fb9dbcca9518083ad1e11276933a2e96f23de604a3a08cc3c80002767d24c
kernel_modules:
  - overlay
  - br_netfilter
k8s_sysctl:
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv4.ip_forward: 1
kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl
kubernetes_support_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg
  - gnupg
  - software-properties-common
