apiVersion: v1
kind: Pod
metadata:
  name: extract-baseline-metrics
  namespace: glasslab-v2
spec:
  containers:
    - name: extract
      image: ubuntu:22.04@sha256:281c5745f657873d78e5531fc5ba8575f46ab7769b94550ac99543f122679986
      command: ["sleep", "3600"]
      volumeMounts:
        - name: artifacts
          mountPath: /mnt/artifacts
  restartPolicy: Never
  nodeSelector:
    glasslab.io/gpu-vendor: nvidia
  volumes:
    - name: artifacts
      persistentVolumeClaim:
        claimName: glasslab-shared-artifacts
