"""Backend-neutral durable-store interface for the research control plane."""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any, Protocol, runtime_checkable

from .schemas import (
    ActionRecord,
    ApprovalStatus,
    ArtifactRecord,
    ContextPacket,
    EventRecord,
    IngestedDatasetRecord,
    JobRecord,
    JobStatus,
    KnowledgeChunk,
    KnowledgeSource,
    RunRecord,
    RunState,
    SourceType,
    TurnRecord,
)


@runtime_checkable
class ResearchStore(Protocol):
    """Operations required from SQLite and PostgreSQL persistence backends.

    The protocol captures the already-shared public application surface.  It
    deliberately excludes backend lifecycle and transaction internals, which
    remain implementation details of each concrete store.
    """

    def ping(self) -> bool: ...
    def append_event(self, *, run_id: str, source: str, event_type: str,
                     payload: dict[str, Any] | None = None) -> EventRecord: ...
    def create_run(self, record: RunRecord, *, one_active_run: bool) -> RunRecord: ...
    def create_terminal_retry(self, record: RunRecord, *, parent_run_id: str,
                              retry_key: str, checkpoint_digest: str,
                              one_active_run: bool) -> tuple[RunRecord, bool]: ...
    def get_terminal_retry_child(self, parent_run_id: str) -> RunRecord | None: ...
    def get_run(self, run_id: str) -> RunRecord: ...
    def list_runs(self) -> list[RunRecord]: ...
    def list_active_runs(self) -> list[RunRecord]: ...
    def replace_run(self, record: RunRecord, *, expected_version: int) -> RunRecord: ...
    def reset_methodology_revision_budget(self, run_id: str, *, reason: str) -> RunRecord: ...
    def transition_run(self, run_id: str, target: RunState, *,
                       source: str = 'orchestrator',
                       payload: dict[str, Any] | None = None,
                       updates: dict[str, Any] | None = None) -> RunRecord: ...
    def save_turn(self, record: TurnRecord) -> TurnRecord: ...
    def list_turns(self, run_id: str) -> list[TurnRecord]: ...
    def mark_running_turns_interrupted(self, run_id: str) -> int: ...
    def save_action(self, record: ActionRecord) -> ActionRecord: ...
    def save_action_with_event(self, record: ActionRecord, *, source: str,
                               payload: dict[str, Any]) -> tuple[ActionRecord, bool]: ...
    def update_action(self, action_id: str, *, approval_status: ApprovalStatus,
                      reviewer: str, reason: str) -> ActionRecord: ...
    def mark_action_honeydew_approved(self, action_id: str, *,
                                      review_turn_id: str) -> ActionRecord: ...
    def mark_action_execution_failed(self, action_id: str, *, reason: str) -> ActionRecord: ...
    def get_action(self, action_id: str) -> ActionRecord: ...
    def list_actions(self, run_id: str) -> list[ActionRecord]: ...
    def create_job_if_absent(self, record: JobRecord) -> tuple[JobRecord, bool]: ...
    def update_job(self, record: JobRecord) -> JobRecord: ...
    def get_job(self, job_id: str) -> JobRecord: ...
    def list_jobs(self, run_id: str, *,
                  statuses: Iterable[JobStatus] | None = None) -> list[JobRecord]: ...
    def save_artifact(self, record: ArtifactRecord) -> ArtifactRecord: ...
    def list_artifacts(self, run_id: str) -> list[ArtifactRecord]: ...
    def save_dataset(self, record: IngestedDatasetRecord) -> IngestedDatasetRecord: ...
    def get_dataset(self, dataset_id: str) -> IngestedDatasetRecord: ...
    def list_datasets(self) -> list[IngestedDatasetRecord]: ...
    def list_events(self, run_id: str, *, after_sequence: int = 0) -> list[EventRecord]: ...
    def save_knowledge_source(self, record: KnowledgeSource) -> KnowledgeSource: ...
    def get_knowledge_source(self, source_id: str) -> KnowledgeSource: ...
    def find_knowledge_source(self, *, digest: str,
                              canonical_uri: str) -> KnowledgeSource | None: ...
    def list_knowledge_sources(self, *, source_types: Iterable[SourceType] | None = None,
                               run_scope: str | None = None) -> list[KnowledgeSource]: ...
    def delete_knowledge_source(self, source_id: str) -> bool: ...
    def delete_knowledge_sources_by_digest(self, digest: str) -> int: ...
    def replace_knowledge_chunks(self, source_id: str,
                                 chunks: list[KnowledgeChunk]) -> list[KnowledgeChunk]: ...
    def list_knowledge_chunks(self, source_id: str) -> list[KnowledgeChunk]: ...
    def search_knowledge_chunks(self, query: str, *, source_ids: list[str] | None = None,
                                limit: int = 10) -> list[dict[str, Any]]: ...
    def save_context_packet(self, packet: ContextPacket) -> ContextPacket: ...
    def get_context_packet(self, packet_id: str) -> ContextPacket: ...
    def list_context_packets(self, run_id: str) -> list[ContextPacket]: ...
