apiVersion: v1
kind: Namespace
metadata:
  name: glasslab-v2
  labels:
    glasslab.io/stack: v2
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
